[versions]
kotlin = "1.7.20"
coroutines = "1.6.4"
sqldelight = "1.5.4"
ktor = "2.2.1"
compose = "1.2.1"
compose-compiler = "1.3.2"
android-gp = "7.3.1"

[plugins]

android-application = { id = "com.android.application", version.ref = "android-gp" }
android-library = { id = "com.android.library", version.ref = "android-gp" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "2.9.2" }

kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "com.squareup.sqldelight", version.ref = "sqldelight" }

[libraries]

compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-material-three = { group = "androidx.compose.material3", name = "material3", version = "1.0.1" }
compose-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version = "1.6.1" }
compose-coil = { group = "io.coil-kt", name = "coil-compose", version = "2.2.2" }

android-desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version = "1.1.5" }

accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version = "0.27.1" }

matrix-olm = { group = "org.matrix.android", name = "olm-sdk", version = "3.2.12" }

unifiedpush = { group = "com.github.UnifiedPush", name = "android-connector", version = "2.0.1" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version = "31.1.1" }

kotlin-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.4.1" }

kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }

sqldelight-android = { group = "com.squareup.sqldelight", name = "android-driver", version.ref = "sqldelight" }
sqldelight-test = { group = "com.squareup.sqldelight", name = "sqlite-driver", version.ref = "sqldelight" }
sqldelight-extensions = { group = "com.squareup.sqldelight", name = "coroutines-extensions", version.ref = "sqldelight" }

ktor-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }

junit = { group = "junit", name = "junit", version = "4.13.2" }
kluent = { group = "org.amshove.kluent", name = "kluent", version = "1.72" }
mockk = { group = "io.mockk", name = "mockk", version = "1.13.3" }

leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version = "2.10" }
